[package]
name = "test-doc-comment"
version = "0.1.0"
authors = ["Robin Stocker"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
doc-comment = "0.3.3"
